version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: openllm-monitor-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: openllm-monitor
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - openllm-network

  # MongoDB Admin UI (Optional)
  mongo-express:
    image: mongo-express:latest
    container_name: openllm-monitor-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - openllm-network

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: openllm-monitor-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - openllm-network

  # Backend API
  backend:
    build: ./backend
    container_name: openllm-monitor-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/openllm-monitor?authSource=admin
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - openllm-network

  # Frontend
  frontend:
    build:
      context: 
        ./frontend
    container_name: openllm-monitor-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://backend:3001/api
      VITE_WS_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - openllm-network

volumes:
  mongodb_data:
    driver: local
  ollama_data:
    driver: local

networks:
  openllm-network:
    driver: bridge
